### ISSUE TITLE
make available through Maven

### ISSUE THREAD

**Issue by fommil** [derabbink/libusb4j#2]
It would be very useful if this library were made available through the Maven repositories, e.g. via sonatype.

**Comment by derabbink** [comment]
I agree with this. But I believe it is important to do a few other things first:
- Increase test coverage (https://github.com/derabbink/libusb4j/issues/7)
- Support complete libusb 1.0 (https://github.com/derabbink/libusb4j/issues/4)
- Write some docs (https://github.com/derabbink/libusb4j/issues/1)
