### ISSUE TITLE
Support HID on OS X

### ISSUE THREAD

**Issue by fommil** [derabbink/libusb4j#6]
Apparently libusb will never be able to get info from OS X without some additional kernel code, see here:

https://github.com/openyou/emokit/issues/54#issuecomment-11721868

Please support this feature, in addition to libusb 1.0.

**Comment by derabbink** [comment]
I suspect a typo: HDI should be HID. Please confirm.

If libusb won't work properly on OS X, that's something this project won't really be able to solve. This project is about making libusb (as is) accessible to java programmers. (Or am I missing your point?)

I'll look into libusb 1.0 support.

**Comment by fommil** [comment]
(typo fixed)

Re: HID, what I mean is for you to expose the relevant methods (Structures, whatever they are called) so that the Java programmer can turn off OS handling of HID devices. I understand that your library simply exposes the relevant low level C libraries, not necessarily providing a user friendly API.

libusb1.0 support would be awesome – try to convince https://github.com/trygvis/javax-usb-libusb1 to use your library as the libusb backend because it would make the whole Java USB stack soooo much easier to use. At the moment, all the JNI is a nightmare.

For now, I've been forced to move over to http://code.google.com/p/javahidapi/ to get my USB device working. It isn't easily distributed or installed. If you could rewrite their JNI backends with your API that would be equally awesome! :-D
